# Generated by Django 3.2.6 on 2023-09-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
    ]
