# Generated by Django 3.2.6 on 2023-11-02 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccine', '0003_alter_vaccine_vaccine_choice'),
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunization_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Taken', 'Taken'), ('Missed', 'Missed')], default='Not administered', max_length=20)),
                ('next_date_of_administration', models.DateField(blank=True, null=True)),
                ('child', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='child.child')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_administration', models.DateField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine_records.immunization_record')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine')),
            ],
        ),
    ]
