# Generated by Django 3.2.6 on 2023-11-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_choice',
            field=models.CharField(choices=[('BCG', 'BCG - Tuberculosis'), ('Polio1', 'OPV  - Polio'), ('DPT-HepB-Hib1', 'DPT-HepB-Hib1 - DPT-HepB-Hib'), ('DPT-HepB-Hib2', 'DPT-HepB-Hib2 - DPT-HepB-Hib'), ('DPT-HepB-Hib3', 'DPT-HepB-Hib3 - DPT-HepB-Hib'), ('Polio2', 'OPV  - Polio'), ('PCV1', 'PCV1  - PCV'), ('Rota', 'Rota - Rotravirus'), ('MRV1', 'MRV1- Measles-Rubella Vaccine'), ('PCV2', 'PCV2  - PCV'), ('MMR', 'MMR- Measles, Mumps, Rubella'), ('DPT-HepB-Hib4', 'DPT-HepB-Hib4 - DPT-HepB-Hib'), ('Polio3', 'OPV  - Polio'), ('HepA', 'Hepatitis A')], max_length=32, null=True, unique=True),
        ),
    ]
